{{- if and .Values.backend.ingress.enabled (ne .Values.backend.ingress.host "") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "quiz-builder.backend.name" . }}-ingress
  labels:
    {{- include "quiz-builder.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.backend.ingress.ingressClassName | default "nginx" }}
    {{- if .Values.backend.ingress.tls.enabled }}
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    {{- end }}
spec:
  rules:
    - host: {{ .Values.backend.ingress.host }}
      http:
        paths:
          - path: {{ .Values.backend.ingress.path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "quiz-builder.backend.name" . }}
                port:
                  number: {{ .Values.backend.service.port }}
  {{- if .Values.backend.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.backend.ingress.host }}
      secretName: {{ .Values.backend.ingress.tls.secretName }}
  {{- end }}
{{- end }}
